GET http://localhost:3000/contact HTTP/1.1

###
POST http://localhost:3000/contact/send HTTP/1.1 
Content-Type: application/json

{ 
  "name": "Omoruyi Iyobosa", 
  "email": "omoruyiiyobosa@yahoo.com", 
  "phone": "08030657191", 
  "message": "Node Js Project to Send Emails using Nodemailer."
}